### PR TITLE
im so getting fired for this

### PR DESCRIPTION
**Pull request by LeWolfYT**

### CODE REVIEW

**Review by sidgames5 — APPROVED** [review]
Im gonna make a few changes to improve this but you are not getting fired

**Review by sidgames5 — CHANGES_REQUESTED** [review]
It looks like you forgot some semicolons

**Comment by sidgames5** [comment]
I also just noticed that in your for loop you just wrote `i = 0`. This needs to be `int i = 0`

**Comment by LeWolfYT** [comment]
ok

**Comment by LeWolfYT** [comment]
> It looks like you forgot some semicolons

where

**Comment by sidgames5** [comment]
Lines 28 and 42

**Review by sidgames5 — APPROVED** [review]

**Comment by sidgames5** [comment]
I think there are some missing imports but i can resolve them

**Pull request merged**
